name: docker_build_image
on:
  workflow_dispatch:
    inputs:
      ImageTag:
        description: 'docker image tag'
        required: true
        default: 'latest'
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Login in Docker Hub
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./flask_app.dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/toast:${{ github.event.inputs.ImageTag }}

      - name: Update Kubernetes resources
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          IMAGE_VERSION: ${{ github.event.inputs.ImageTag }}
        run: |
          cd kustomize/
          kustomize edit set image flask-app=$DOCKER_USERNAME/flask-app:$IMAGE_VERSION
          cat kustomization.yaml
          yq e ".spec.template.spec.containers.0.image |=\"$DOCKER_USERNAME/flask-app:$IMAGE_VERSION\"" -i 01_deployment.yaml -I 2
      
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update image tag by Github action workflow docker_build_image"
      
      - name: Puhs code
        uses: ad-m/github-push-action@master
        with:  
          github_token: ${{ secrets.GITHUB_TOKEN }}
